apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: holidays-data-pvc
  namespace: holidays
  labels:
    app: holidays-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
